version: "3.1"

services:
  back_test_db:
    image: postgres:11.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=back_test
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=back_test
    volumes:
      - back_test-db:/var/lib/postgresql/data
volumes:
  back_test-db: