version: "3.1"
services:
  stubs:
    image: springcloud/spring-cloud-contract-stub-runner:2.1.2.RELEASE
    environment:
      - STUBRUNNER_IDS=com.qajungle.talks.integratedandisolated.backtest:back-test.infrastructure:+:stubs:9876
      - STUBRUNNER_REPOSITORY_ROOT=${REMOTE_REPOSITORY}
      - STUBRUNNER_USERNAME=${REMOTE_USER}
      - STUBRUNNER_PASSWORD=${REMOTE_PASSWORD}
      - STUBRUNNER_STUBS_MODE=REMOTE
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8083"
      - "127.0.0.1:9876:9876"
    